# Generated by Django 5.1.1 on 2024-09-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pid',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
