# Generated by Django 5.1.1 on 2024-09-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_pid'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
    ]
