# Generated by Django 5.1.1 on 2024-09-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='pid',
            field=models.CharField(default='000000', max_length=6, unique=True),
        ),
    ]
