# Generated by Django 5.1.1 on 2024-10-12 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='user_pid',
        ),
        migrations.AlterField(
            model_name='employee',
            name='managerid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='home.manager'),
        ),
    ]
