# Generated by Django 5.1.1 on 2024-10-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_manager_user_pid_alter_employee_managerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empid',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='managerid',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
