# Generated by Django 5.1.1 on 2024-10-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='review_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='submission_date',
            field=models.DateField(null=True),
        ),
    ]
