# Generated by Django 5.1.1 on 2024-10-13 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_forms_review_date_alter_forms_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formassignedbyto',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.employee'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employees', models.ManyToManyField(related_name='groups', to='home.employee')),
                ('managers', models.ManyToManyField(related_name='managed_groups', to='home.manager')),
            ],
        ),
        migrations.AddField(
            model_name='formassignedbyto',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.group'),
        ),
    ]
