# Generated by Django 5.0.2 on 2024-10-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_formassignedbyto_employee_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='doj',
            field=models.DateField(blank=True, null=True),
        ),
    ]
