# Generated by Django 5.0.2 on 2024-10-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_employee_doj'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formassignedbyto',
            unique_together={('form', 'employee')},
        ),
    ]
