# Generated by Django 5.1.1 on 2024-10-17 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_employee_doj'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('acknowledged', models.BooleanField(default=False)),
                ('viewed_date', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_date', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employee')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.notice')),
            ],
        ),
    ]
