# Generated by Django 5.0.2 on 2024-10-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_noticestatus'),
        ('home', '0010_filledform'),
    ]

    operations = [
    ]
