# Generated by Django 5.1.1 on 2024-10-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_merge_0009_noticestatus_0010_filledform'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='max_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='min_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
