# Generated by Django 5.1.1 on 2024-10-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_forms_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formassignedbyto',
            name='assign_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
