# Generated by Django 5.1.3 on 2024-11-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_formassignedbyto_assign_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formassignedbyto',
            unique_together={('form', 'employee', 'group')},
        ),
        migrations.AddField(
            model_name='formassignedbyto',
            name='peer_review',
            field=models.BooleanField(default=False),
        ),
    ]
