# Generated by Django 5.1.3 on 2024-11-08 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_formassignedbyto_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formassignedbyto',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.manager'),
        ),
    ]
